# coding: utf-8

"""
    Apicurio Registry API [v2]

    Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`.   # noqa: E501

    The version of the OpenAPI document: 2.4.x
    Contact: apicurio@lists.jboss.org
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from apicurioregistryclient import schemas  # noqa: F401


class LogLevel(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "DEBUG": "DEBUG",
            "TRACE": "TRACE",
            "WARN": "WARN",
            "ERROR": "ERROR",
            "SEVERE": "SEVERE",
            "WARNING": "WARNING",
            "INFO": "INFO",
            "CONFIG": "CONFIG",
            "FINE": "FINE",
            "FINER": "FINER",
            "FINEST": "FINEST",
        }
    
    @schemas.classproperty
    def DEBUG(cls):
        return cls("DEBUG")
    
    @schemas.classproperty
    def TRACE(cls):
        return cls("TRACE")
    
    @schemas.classproperty
    def WARN(cls):
        return cls("WARN")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("ERROR")
    
    @schemas.classproperty
    def SEVERE(cls):
        return cls("SEVERE")
    
    @schemas.classproperty
    def WARNING(cls):
        return cls("WARNING")
    
    @schemas.classproperty
    def INFO(cls):
        return cls("INFO")
    
    @schemas.classproperty
    def CONFIG(cls):
        return cls("CONFIG")
    
    @schemas.classproperty
    def FINE(cls):
        return cls("FINE")
    
    @schemas.classproperty
    def FINER(cls):
        return cls("FINER")
    
    @schemas.classproperty
    def FINEST(cls):
        return cls("FINEST")
