# coding: utf-8

"""
    Apicurio Registry API [v2]

    Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`.   # noqa: E501

    The version of the OpenAPI document: 2.3.1.Final
    Contact: apicurio@lists.jboss.org
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from apicurioregistryclient import schemas  # noqa: F401


class SearchedVersion(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Models a single artifact from the result set returned when searching for artifacts.
    """


    class MetaOapg:
        required = {
            "references",
            "createdBy",
            "contentId",
            "globalId",
            "state",
            "type",
            "createdOn",
            "version",
        }
        
        class properties:
            createdOn = schemas.StrSchema
            createdBy = schemas.StrSchema
        
            @staticmethod
            def type() -> typing.Type['ArtifactType']:
                return ArtifactType
        
            @staticmethod
            def state() -> typing.Type['ArtifactState']:
                return ArtifactState
            globalId = schemas.Int64Schema
            version = schemas.StrSchema
            contentId = schemas.Int64Schema
            
            
            class references(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ArtifactReference']:
                        return ArtifactReference
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ArtifactReference'], typing.List['ArtifactReference']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'references':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ArtifactReference':
                    return super().__getitem__(i)
            name = schemas.StrSchema
            description = schemas.StrSchema
            
            
            class labels(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'labels':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
        
            @staticmethod
            def properties() -> typing.Type['Properties']:
                return Properties
            __annotations__ = {
                "createdOn": createdOn,
                "createdBy": createdBy,
                "type": type,
                "state": state,
                "globalId": globalId,
                "version": version,
                "contentId": contentId,
                "references": references,
                "name": name,
                "description": description,
                "labels": labels,
                "properties": properties,
            }
    
    references: MetaOapg.properties.references
    createdBy: MetaOapg.properties.createdBy
    contentId: MetaOapg.properties.contentId
    globalId: MetaOapg.properties.globalId
    state: 'ArtifactState'
    type: 'ArtifactType'
    createdOn: MetaOapg.properties.createdOn
    version: MetaOapg.properties.version
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdOn"]) -> MetaOapg.properties.createdOn: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdBy"]) -> MetaOapg.properties.createdBy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> 'ArtifactType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["state"]) -> 'ArtifactState': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["globalId"]) -> MetaOapg.properties.globalId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contentId"]) -> MetaOapg.properties.contentId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["references"]) -> MetaOapg.properties.references: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["labels"]) -> MetaOapg.properties.labels: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["properties"]) -> 'Properties': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["createdOn", "createdBy", "type", "state", "globalId", "version", "contentId", "references", "name", "description", "labels", "properties", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdOn"]) -> MetaOapg.properties.createdOn: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdBy"]) -> MetaOapg.properties.createdBy: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> 'ArtifactType': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["state"]) -> 'ArtifactState': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["globalId"]) -> MetaOapg.properties.globalId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contentId"]) -> MetaOapg.properties.contentId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["references"]) -> MetaOapg.properties.references: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["labels"]) -> typing.Union[MetaOapg.properties.labels, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["properties"]) -> typing.Union['Properties', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["createdOn", "createdBy", "type", "state", "globalId", "version", "contentId", "references", "name", "description", "labels", "properties", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        references: typing.Union[MetaOapg.properties.references, list, tuple, ],
        createdBy: typing.Union[MetaOapg.properties.createdBy, str, ],
        contentId: typing.Union[MetaOapg.properties.contentId, decimal.Decimal, int, ],
        globalId: typing.Union[MetaOapg.properties.globalId, decimal.Decimal, int, ],
        state: 'ArtifactState',
        type: 'ArtifactType',
        createdOn: typing.Union[MetaOapg.properties.createdOn, str, ],
        version: typing.Union[MetaOapg.properties.version, str, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        labels: typing.Union[MetaOapg.properties.labels, list, tuple, schemas.Unset] = schemas.unset,
        properties: typing.Union['Properties', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SearchedVersion':
        return super().__new__(
            cls,
            *args,
            references=references,
            createdBy=createdBy,
            contentId=contentId,
            globalId=globalId,
            state=state,
            type=type,
            createdOn=createdOn,
            version=version,
            name=name,
            description=description,
            labels=labels,
            properties=properties,
            _configuration=_configuration,
            **kwargs,
        )

from apicurioregistryclient.model.artifact_reference import ArtifactReference
from apicurioregistryclient.model.artifact_state import ArtifactState
from apicurioregistryclient.model.artifact_type import ArtifactType
from apicurioregistryclient.model.properties import Properties
