name: Generate TypeScript API client

on:
  repository_dispatch:
    types: [on-oas-updated]

jobs:
  generate:
    name: Generate TS client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download OpenAPI document
        run: | 
          mkdir -p tmp
          curl https://raw.githubusercontent.com/Apicurio/apicurio-registry/master/${{ github.event.client_payload.openapi_file_path }} > tmp/input-schema.json
      - name: Preprocess input schema
        run: bash <(curl -s https://raw.githubusercontent.com/Apicurio/apicurio-registry-client-sdk-go/main/hack/scripts/preprocess-schema.sh)
      - uses: craicoverflow/openapi-generator-action@v1
        with:
          generator: python
          input: tmp/input-schema.json
          git-user-id: Apicurio
          git-repo-id: apicurio-registry-client-sdk-python
          additional-properties: "packageName=apicurioregistryclient"
          ignore-file-override: .openapi-generator-ignore
      - name: Clean up temp files
        run: rm -r tmp
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            generated:
              - '**'

      - name: Create Pull Request
        if: steps.changes.outputs.generated == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          branch-suffix: short-commit-hash
          branch: generate-sdk
          title: "[generated] Update API client"
          commit-message: "chore: update API client"
          body: |
            Automated update of the Apicurio Registry SDK
